### ISSUE TITLE
IR02, IR03

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wms#118]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

These requirements for compliance with the 'basic WMS' conformance class should perhaps be included as an explicit abstract test case.
# Proposed Change

Add this as a test case with reference to an explicit external conformance class 'OGC WMS 1.3.0. Basic WMS Server'.

**Comment by timrduffy** [comment]
Again, we will probably need to cater for WMS 1.1.1 services somehow

**Comment by timrduffy** [comment]
should be conformance to the _basic WMS **server**_

**Comment by timrduffy** [comment]
Essentially this is the same issue as #119 leaving open for discussion

**Comment by jensscheerlinck** [comment]
This will be addressed in the new ATS structure. See inspire-eu-validation/ats-cross-cutting#16
