### ISSUE TITLE
IR02, IR03

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wms#119]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

The requirements related to conformance with the WMS standard are not represented in the ATS.
# Proposed Change

The ATS should reference the OGC WMS conformance class(es) that are a dependency (but not reference individual WMS tests). With a view to ETSs for those, in general, the tests for WMS 1.3.0 should be provided by OGC CITE (which would require the WMS 1.3.0 tests to be amended to be independent of any test dataset).

**Comment by timrduffy** [comment]
How does a test for conformance against WMS 1.3.0 work for a service provided as a WMS 1.1.1 service?  Agreed we should be using appropriate CITE tests for conformance to the standard.

**Comment by timrduffy** [comment]
Think this a good idea, but leaving open for discussion

**Comment by jensscheerlinck** [comment]
This will be addressed in the new ATS structure. See https://github.com/inspire-eu-validation/ats-cross-cutting/issues/16
