### ISSUE TITLE
IR37 (missing test case)

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wms#125]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

It is not clear why this requirement cannot be tested. 
It seems that this requirement refers to the inclusion of a unique resource identifier in an external metadata record (scenario 1 û metadata record as online resource). 
# Proposed Change

Clarify whether this test should be added, it could also be covered by a more general test case that retrieves the metadata record and checks whether resource identifiers are present.

**Comment by timrduffy** [comment]
Table 4 of TG for the implementation of INSPIRE view services tells us that _Unique Resource Identifier_ maps to WMS metadata (not an external metadata resource), that is:

 Unique Resource Identifier = wms:Identifier + wms:AuthorityURL.

So a test on whether a layer can be uniquely identified through its wms:Identifiers (such an identifier identifies the authority) should be possible.

**Comment by nmtoken** [comment]
IR 37 and IR 38 should be considered together for formulating the ATS tests

**Comment by jensscheerlinck** [comment]
Linked IR37 to test case [A.32.IR38.layer.identifier.node](A.32.IR38.layer.identifier.node.md)
