### ISSUE TITLE
IR49 (missing)

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wms#126]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

It is not clear why IR49 on category layer MetadataURL cannot be tested.

**Comment by timrduffy** [comment]
Agreed.  (I'm reading category layers to be sub layers within a group) 

In fact as we will need to test such layers because the restrictions on harmonized layer names will force many providers to set up group layers (with member category layers)

**Comment by jensscheerlinck** [comment]
Created [new test case](https://github.com/inspire-eu-validation/ats-view-wms/blob/ats-issue-resolution/category.layers.md) to address IR49
