### ISSUE TITLE
missing for IR09

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wms#128]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

It is claimed that this requirement is not testable. This seems wrong.
# Proposed Change

It seems that this could be testable in both scenarios:
- scenario 1: Retrieve the URL to the Discovery service from &lt;metadataURL&gt;. Verify if the metadata record exists and is valid. 
- scenario 2: The ATS could require an optional test run parameter to indicate the corresponding discovery service. A query could check whether there is indeed a corresponding metadata record in the discovery service.

**Comment by timrduffy** [comment]
_scenario 2: The ATS could require an optional test run parameter to indicate the corresponding discovery service. A query could check whether there is indeed a corresponding metadata record in the discovery service._

There isn't a corresponding discovery service in a scenario 2 response, The metadata for the service is in the extended capabilities section of the service

**Comment by nmtoken** [comment]
scenario 1

the URL may not point to a discovery service

scenario 2 

there is no (or usually there is no) URL

So the only sensible thing to test is to find **this** service in one of the central discovery services for INSPIRE...

**Comment by aquaglia** [comment]
Well, from the INSPIRE Geoportal perspective, in order to find this View Service, we have started from the metadata taken from the National Discovery Service.
So, once we reach this View Service it would make sense to check that the pieces of information actually match.

**Comment by cportele** [comment]
I have set this to "rejected"/"wontfix" as we can conclude from the discussion that we cannot reliably find the service metadata entry in the discovery service from the information in the view service (which is the system under test). 

As there are cross-component consistency issues as pointed out by Angelo, I have flagged this, too.
