### ISSUE TITLE
If MetadataURL is specified in the Extended Capabi...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wms#129]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

If MetadataURL is specified in the Extended Capabilities some elements  (like the resource title, abstract, keywords) will be mapped twice: once in the standard capabilities elements and once in the linked metadata document.
There is no guidance about this.

**Comment by cportele** [comment]
Correct, but this is not an ATS issue, but something that needs to be addressed in the Technical Guidance first.
