### ISSUE TITLE
When the resource referenced by a MetadataURL elem...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wms#130]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

When the resource referenced by a MetadataURL element (in the Extended Capabilities or in the layer element) is accessed, the response that comes back is usually wrapped inside a GetRecordById.
However, according to the OGC WMS 1.3.0 specifications, it can be just the metadata file.
If this is allowed, it should be explained.

**Comment by cportele** [comment]
Agreed. In the WMS technical guidelines the requirement is "The URL shall be either an HTTP/GET call on the GetRecordById operation of the Discovery Service or a direct link to the ISO 19139 metadata document." 

Proposed resolution:
- Update network service test cases to allow either a response to a GetRecordById request or a gmd:MD_Metadata document.

**Comment by cportele** [comment]
Proposed resolution accepted by default. See [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10#Next-steps).
