### ISSUE TITLE
The Prerequisites contain  the following sentences...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wms#131]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

The Prerequisites contain  the following sentences, the meaning of which is really not clear:

Test for the existence of default element namespace.
Test for the existence of the namespaces for INSPIRE View Services inspire_vs and inspire_common.

**Comment by cportele** [comment]
Resolved by https://github.com/inspire-eu-validation/ats-cross-cutting/issues/9

**Comment by cportele** [comment]
Status changed to "wontfix" as inspire-eu-validation/ats-cross-cutting#9 will implement this consistently.
