### ISSUE TITLE
Question about View Service validation

### ISSUE THREAD

**Issue by OscarD31** [inspire-eu-validation/ats-view-wms#134]
Good morning!

Just a question.

In the old INSPIRE validator you could validate a WMS service with its GetCapabilities URL.

The new validator doesn't have a test suite for WMS services. Taking into account that this repository (view-service) exists, does that mean the WMS validation will be included as a test suite in the "ets-repository" sooner or later?

Thanks!

**Comment by michellutz** [comment]
Dear Oscar,

yes, it is planned to add also ETSs for view services (WMS, WMTS) to the INSPIRE test framework over the coming months. 

After consulting Member States about the priority for adding the missing ATS and ETS to the test framework, we will probably proceed in the following order:
- Metadata v2.0 (ATS and ETS) 
- Annex II+III data specifications (ATS, ETS) 
- View Services – WMS & WMTS (ETS)
- Discovery Services (ETS)
- Download Services – SOS & WCS (ATS, ETS) 

Best regards,
Michael

**Comment by OscarD31** [comment]
Thanks for the info!
