### ISSUE TITLE
Within what is considered as Conformance Class Layer-Metadata there are ATS specific to a type of service

### ISSUE THREAD

**Issue by PaulaRodrigo-Geograma** [inspire-eu-validation/ats-view-wms#136]
There are some tests that apply to both types of services. If they are not common, they should be defined in their specific conformance class (ISO 19128 or WMTS 1.0.0). For example:

**supported-and-response-languages-node**

_https://github.com/inspire-eu-validation/view-service/blob/3.11/layer-metadata/supported-and-response-languages-node.md_

They are only assigned to the groups of requirements of ISO19128, but not in the WMS:

_https://github.com/inspire-eu-validation/view-service/tree/3.11/layer-metadata#iso-19128-profile_

**Comment by michellutz** [comment]
[2017.4 meeting 2018-04-19] Distinguish clearly between tests for WMS and for WMTS, but consider whether there are some common tests that could be factored out (similar to the data or metadata ATS) when working on the the refactoring proposal to be discussed in the next sub-group meeting.

**Comment by michellutz** [comment]
The change has been implemented in the revised ATS for view services. So this issue can be closed.
