### ISSUE TITLE
Default style not defined

### ISSUE THREAD

**Issue by PaulaRodrigo-Geograma** [inspire-eu-validation/ats-view-wms#145]
For cases in which the default style is not indicated, how could requirements 43 and 44 be checked?

Reference: [Review Default Style ATS](https://github.com/inspire-eu-validation/view-service/blob/review-ats-tg_3.11/iso-19128/review-default-style.md)

**Comment by michellutz** [comment]
The IRs only require the following metadata for the styles of each layer:
- List of the rendering styles available for the layer.
- A style shall be composed of a title and a unique identifier

So strictly speaking, only this should be tranlated into requirements in the TGs and tested in the ATS/ETS.

Requirements 42, 43 should therefore be changed into notes or recommendations informing on the requirements defined in the IRs for data interoperability. The question then of course is whether/how the requirements on layers/styles defined in those IRs can be tested (automatically).

**Comment by danielnavarrogeo** [comment]
The test for requirement 42 has been updated and it is currently ready for review in branch [review-ats-tg_3.11](https://github.com/inspire-eu-validation/view-service/blob/review-ats-tg_3.11/iso-19128/at42-getcapabilities-layer-default-style.md).

The test checks if a layer shall provide a default layer based on the portrayal section of its INSPIRE Data Theme Specification. If it does, check if the default style is provided, otherwise the test pass.

**Comment by michellutz** [comment]
Please create a bugfix-1.1 branch (as for inspire-eu-validation/data) and make a pull request to that branch, requesting a review from me or Marco.

Thanks, m

**Comment by MarcoMinghini** [comment]
Dear @danielnavarrogeo and @inakidiazdecerio, can you confirm that this PR was done and merged (as discussed in [the last 2017.4 sub-group meeting](https://webgate.ec.europa.eu/fpfis/wikis/display/InspireMIG/2017.4+meeting+%239+2019-01-17)), so that we can close this issue?

**Comment by danielnavarrogeo** [comment]
Dear @MarcoMinghini,

This question was made before we re-write the ATS for view services. As you can see, the link to [Review Default Style ATS](https://github.com/inspire-eu-validation/view-service/blob/review-ats-tg_3.11/iso-19128/review-default-style.md) from the first comment does not exist anymore.

We have approached this situation as described in [at-42](https://github.com/inspire-eu-validation/view-service/blob/review-ats-tg_3.11/iso-19128/at42-getcapabilities-layer-default-style.md) and it is implemented according to that in the ETS for WMS.

Therefore, I think we can safely close this issue.

Thanks.
