### ISSUE TITLE
Catalan as supported language in capabilities

### ISSUE THREAD

**Issue by danicgc** [inspire-eu-validation/ats-view-wms#150]
When including Catalan ("cat") as one of the supported languages in the capabilities document, the _at04-getcapabilities-xml-schema-validation_ throws the following error message, despite being a regional language included on the INSPIRE common.xsd schema (and so having an ISO 639-2/B alpha 3 code):

Schema not valid: [org.xml.sax.SAXException: Fatal error: org.xml.sax.SAXParseException; lineNumber: 99; columnNumber: 70; cvc-enumeration-valid: Value 'cat' is not facet-valid with respect to enumeration '[bul, cze, dan, dut, eng, est, fin, fre, ger, gre, hun, gle, ita, lav, lit, mlt, pol, por, rum, slo, slv, spa, swe]'. It must be a value from the enumeration. Response did not validate against schema 'http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd'.]

**Comment by carlospzurita** [comment]
Dear @danicgc 

We would kindly ask you to move this issue to the [community space](https://github.com/inspire-eu-validation/community/issues/), as we centralize there all issues related to the INSPIRE Validator. This repository is inteded for storing ATS, and is not being actively monitorized.

**Comment by danicgc** [comment]
Opened as https://github.com/inspire-eu-validation/community/issues/380 in the community space
