### ISSUE TITLE
For requirements on service metadata elements: add scenario 1 or 2

### ISSUE THREAD

**Issue by thijsbrentjens** [inspire-eu-validation/ats-view-wms#75]
Several requirements are only applicable if scenario 2 (for metadata elements of the service metadata) is implemented by the service. These requirements now describe tests for the ExtendedCapabilities elements, but for scenario 1 most ExtendedCapabilities elements are not required. Should we add a prerequisite "for scenario 2 only" or something similar to these requirements?

For example: req 11, 12, 15, 21 (ect)

**Comment by boehmesven** [comment]
good idea. I created a new page with the assignments of the TG Req to the scenarios:

https://github.com/inspire-eu-validation/ats-view-wms/blob/master/metadata-scenarios.md
