### ISSUE TITLE
For tests on Layers: only consider Layers with a wms:Name?

### ISSUE THREAD

**Issue by thijsbrentjens** [inspire-eu-validation/ats-view-wms#76]
In WMS you can have layers with and without a Name. The latter are group layers that can't be used for GetMap etc. 
Maybe it's not relevant here, in the ATS, but more an implementation issue. But should we mention that only Layers that have a wms:Name are subject of the tests for for example Keywords, Abstracts, BoundingBox, MetadataURL etc?

**Comment by boehmesven** [comment]
I would agree. The text in the implementing specifications has the same meening (for me):

7.2.4.6.3 Name
If, and only if, a layer has a <Name>, then it is a map layer that can be requested by using that Name in the LAYERS parameter of a GetMap request. A Layer that contains a <Name> element is referred to as a “named layer” in this International Standard. If the layer has a Title but no Name, then that layer is only a category title for all the layers nested within. A server that advertises a Layer containing a Name element shall be able to accept that Name as the value of LAYERS argument in a GetMap request and return the corresponding map. A client shall not attempt to request a layer that has a Title but no Name.

**Comment by nmtoken** [comment]
Even those layers that have a name may not be in scope.  For example do we want to apply all the tests to the root layer?
